config/routes.rb
Rails.application.routes.draw do
  root to: "frontend#index"
  resources :messages, :only => [:index, :new, :create, :show]
  get '/inbound_messages' => "inbound_messages#index"
end

app/models/inbound_message.rb
class InboundMessage
  define_singleton_method :inbound do |from|
    Message.create( body: "We are not human and apologize.", from: from[:To], to: from[:From] )
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  before_create :send_message
  validates :body, presence: true

private
  define_method :send_message do
    response = RestClient::Request.new(
      :method => :post,
      :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_USER_ID']}/Messages.json",
      :user => ENV['TWILIO_USER_ID'],
      :password => ENV['TWILIO_USER_PASSWORD'],
      :payload => { :Body => body,
                    :From => from,
                    :To => to }
    ).execute
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  define_method :index do
    
  end
end

app/controllers/inbound_messages_controller.rb
class InboundMessagesController < ApplicationController
  define_method :index do
    InboundMessage.inbound params
  end
  define_method :show do

  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  define_method :index do
    @messages = Message.all
  end

  define_method :new do
    @message = Message.new
  end

  define_method :create do
    @message = Message.new message_params
    if @message.save
      flash[:notice] = "Your message was sent!"
      redirect_to messages_path
    else
      render 'new'
    end
  end

  define_method :show do
    @message = Message.find params[:id]
  end

  private
  define_method :message_params do
    params.require(:message).permit(:to, :from, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/frontend/index.html.erb
<div class="col-xs-3 col-xs-offset-5">
  <%= link_to "Send Text Message", new_message_path, class: "btn-lg btn-primary" %>
</div>

app/views/inbound_messages/index.html.erb
<h1>INBOUND SHOW</h1>

app/views/inbound_messages/show.html.erb
<h1>INBOUND</h1>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
    <h3>Please try again:</h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      <% end %>
    </ul>
<% end %>
   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twiliotext</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <div class="jumbotron">
      <h1><%= link_to "Twilio Text", root_path %></h1>
      <p>Send an SMS text.</p>
    </div>
  </div>

<%= flash[:notice] %>
<%= yield %>

</body>
</html>

app/views/messages/_create_messages.html.erb
<div class="row">
  <div class="col-xs-4 col-xs-offset-5">
    <%= form_for @message do |m| %>
      <%= m.label :to, class: "label label-primary"%> <br \>
      <%= m.text_field :to, value: '9718088960'%> <br \>
      <%= m.label :from, class: "label label-primary" %> <br \>
      <%= m.text_field :from, value: '2023354509' %> <br \>
      <%= m.label :body, class: "label label-primary" %> <br \>
      <%= m.text_field :body, class: 'messageBody', id: 'messageBody' %> <br \>
      <%= m.submit "Send Text", class: "btn-lg btn-warning" %>
    <%end%>
  </div>
</div>

app/views/messages/index.html.erb
<div class="row">
  <div class="col-xs-4 col-xs-offset-6 ">
    <%= link_to "New Message", new_message_path, class: "btn-lg btn-info"%>
  </div>
</div>

app/views/messages/new.html.erb
<%= render 'layouts/errors', object: @message %>

<%= render 'create_messages' %>
   

app/views/messages/show.html.erb
<div class="row">
  <%= @message.body %>
</div>

<%= link_to "Home", root_path %> 